Repository BrainLesion/tutorials, pull requests merged in 2024-03, with the labels that each got.

#36 Fix/broken figure
  panoptica/figures/semantic.png
Labels: bug, documentation

#34 31 update aurora tutorial
  AURORA/tutorial.ipynb
Labels: enhancement

#45 40 feature request we need issue templates to get more meaningful issues
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
Labels: documentation, enhancement
